name: Auto commit

on:
  schedule:
    - cron: "15 4,8,15 * * 0-2"
    - cron: "0 8-20 * * 1-5"
    - cron: "10 3-11 4-20 * *"

jobs:
  auto_commit:
    name: "Auto push a commit to my repo"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create sample file with just timestamp
        run: date +%s >> report_timestamp.txt
      - name: Commit file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "tnvietanh"
          git config user.email "tnvietanh@users.noreply.github.com"
          git add .
          git commit -am "Automated report"
          git push
